Ensure old ssl certs not copied in nginx role
UCL-MIRSG/ansible-collection-infra pull request #149
Opened 2024-11-28 16:49 UTC by ruaridhg

Fixes #145 

Only copy server certificates to nginx if hashes are different between cached certificates and new certificates.

Do we want to also copy the latest certificate back to the cache as well?

2024-11-28 18:39 UTC, drmatthews requested changes
Unfortunately I don't think this is going to solve our problem on its own. If CS put the new cert in the path defined by `nginx_ssl_cert_file`, while the one in the cache is the old cert, the checksums will be different and the new cert will get overwritten (i.e. it still requires someone to copy the newly placed certs into the cache location).

2024-11-29 10:04 UTC, ruaridhg commented
> Unfortunately I don't think this is going to solve our problem on its own. If CS put the new cert in the path defined by `nginx_ssl_cert_file`, while the one in the cache is the old cert, the checksums will be different and the new cert will get overwritten (i.e. it still requires someone to copy the newly placed certs into the cache location).

Ah, yep that makes sense. Okay, I'll work on this more on Monday.

2024-11-30 09:20 UTC, p-j-smith requested changes
to add to @drmatthews point, the `x509_certificate_info_module` will probably be useful here -  you could check and compare the expiry dates ([`not after`](https://docs.ansible.com/ansible/latest/collections/community/crypto/x509_certificate_info_module.html#return-not_after)) of the certs. It might also be worth setting `backup: true` when copying the cert and key from cache

2024-12-02 15:23 UTC, p-j-smith requested changes
looking good! There are quite a few tasks that run `when: nginx_use_ssl` - perhaps we could put them into a separate file and include the file when SSL is enabled?

2024-12-04 14:01 UTC, p-j-smith reviewed
@ruaridhg I've pushed some changes to:
- check certificate expiry date in the nginx role before copying to/from cache
- added variable to `ssl_certificates` role to set the expiry date (all usages of the role set to the default of 10 years, except for the nginx tests where two certs are generated)
- update tomcat version

2024-12-04 14:03 UTC, p-j-smith submitted a review, later dismissed

2024-12-04 14:38 UTC, drmatthews commented on roles/ssl_certificates/README.md
>    csr_common_name: "db"
```suggestion
  csr_common_name: db
```

2024-12-04 14:43 UTC, drmatthews reviewed
Looks great!

Very minor (and ignorable) but I removed some unnecessary double quotes from the example in the `README.md` file of the `nginx`.

2024-12-04 15:28 UTC, drmatthews approved these changes
🚀

2024-12-04 15:43 UTC, ruaridhg commented
> @ruaridhg I've pushed some changes to:
> 
> * check certificate expiry date in the nginx role before copying to/from cache
> * added variable to `ssl_certificates` role to set the expiry date (all usages of the role set to the default of 10 years, except for the nginx tests where two certs are generated)
> * update tomcat version

Thanks, this looks like it covers everything we discussed!

2024-12-04 15:46 UTC, merged