Add `omero_server` role and playbook
UCL-MIRSG/ansible-collection-infra pull request #53
Opened 2024-01-15 12:03 UTC by drmatthews

2024-03-18 08:47 UTC, drmatthews commented on playbooks/install_xnat.yml
> +  hosts: xnat
Renamed to distinguish this group as VMs which host the XNAT web application.

2024-03-18 08:47 UTC, drmatthews commented on playbooks/install_xnat.yml
> +  hosts: xnat
Renamed to distinguish this group as VMs which host the XNAT web application.

2024-03-26 11:01 UTC, drmatthews commented on meta/requirements.yml
> +roles:
The role versions are pinned here as newer versions no longer support EL 9.

2024-03-26 11:02 UTC, drmatthews commented on molecule_configs/centos7_base_config.yml
> +      stdout_callback: yaml
Nice formatting of molecule stdout

2024-03-26 11:03 UTC, drmatthews commented on playbooks/group_vars/db.yml
> -  database_name: "{{ xnat_db.postgres_xnat_database }}"
`postgres_xnat_database`, `postgres_xnat_user` and `postgres_xnat_password` have been changed to match what was set for OMERO - `postgresql_database` etc. I don't think the `xnat` part of the name is needed.

2024-03-26 11:06 UTC, drmatthews commented on playbooks/group_vars/db.yml
> -  client_ip: "{{ xnat_web_server.ip }}"
`xnat_web_server` has been renamed to `web_server` so that these vars can be used for the database component of OMERO deployments.

2024-03-26 11:08 UTC, drmatthews commented on playbooks/molecule/centos7_xnat/molecule.yml
> -      - ${MOLECULE_SCENARIO_DIRECTORY}/../resources/xnat/files/resolv.conf:/etc/resolv.conf
`resolv.conf` is used by both XNAT and OMERO tests.

2024-03-26 11:09 UTC, drmatthews commented on playbooks/molecule/centos7_xnat/molecule.yml
> -    prepare: ../resources/xnat/prepare.yml
I'm also using the `prepare.yml` playbook for both sets of tests.

2024-03-26 11:09 UTC, drmatthews commented on playbooks/molecule/resources/omero/inventory/group_vars/all/common.yml
Following the same naming as the group vars set for the XNAT tests.

2024-03-26 11:10 UTC, drmatthews commented on playbooks/molecule/resources/omero/inventory/group_vars/all/server.yml
Again following the naming used for the group vars in the XNAT tests.

2024-03-26 11:12 UTC, drmatthews commented on playbooks/molecule/resources/shared/prepare.yml
Used by both XNAT and OMERO tests.

2024-03-26 11:12 UTC, drmatthews commented on playbooks/molecule/resources/xnat/inventory/group_vars/all/all.yml
> +xnat_home_dir: "{{ xnat_root_dir }}/home"
Moved from playbook level

2024-03-26 11:14 UTC, drmatthews commented on playbooks/molecule/resources/xnat/inventory/group_vars/db.yml
Moved to the playbook level - `playbooks/group_vars/db.yml`

2024-03-26 12:15 UTC, p-j-smith requested changes
looks good! I've gone through it as best I can but there are lots of omero-related tasks that I can't really comment on.

Just a few questions around some variables set at playbook level vs inventory

2024-03-26 12:15 UTC, p-j-smith commented on roles/omero_server/README.md
> +directly into OMERO.
```suggestion
See [ome/design#70](https://github.com/ome/design/issues/70) for a proposal to
add support for a conf.d style directory directly into OMERO.
```

2024-03-26 12:15 UTC, p-j-smith commented on roles/omero_server/templates/systemd-system-omero-server-service.j2
> +After=postgresql-14.service
not for this PR, but should we add this to the tomcat service config for XNAT so it doesn't start before postgres?

2024-03-26 12:25 UTC, drmatthews commented on playbooks/group_vars/xnat.yml
> +firewalld_allow_public_access: true
Yep, they are basically the same. Just need to have a look at setting custom locations in the nginx role.

2024-03-26 12:26 UTC, drmatthews commented on playbooks/group_vars/xnat.yml
> +xnat_wait_for_tomcat: 15
Good catch - thanks.

2024-03-26 12:27 UTC, drmatthews commented on roles/omero_server/README.md
> +This is only used when initialising a new database.
OMG...

2024-03-26 12:27 UTC, drmatthews commented on roles/omero_server/README.md
> +environment variables. Python virtualenv
D'oh

2024-03-26 17:28 UTC, p-j-smith approved these changes
nice! So to summarise the changes that need to be made for any repos using these roles / playbooks (based on XNAT variable names):

- rename `xnat_db` variable to `db_server`
- rename `xnat_web_server` variable to `web_server`
- rename `postgres_xnat_*` variables to `postgresql_*`
- remove ~`firewalld_internal_zone_sources`~ and `firewalld_internal_zone_open_services` from then `db` inventory group vars as these are now set at the playbook level
- rename `web` group to `xnat`, and rename the corresponding inventory group vars file (`web.yml` -> `xnat.yml`)
- remove `firewalld_internal_zone_ports`, `firewalld_work_zone_ports`, and `firewalld_public_zone_ports` from the `xnat` inventory group vars as these are now set at the playbook level
- define `xnat_data_dir`, `xnat_root_dir`, and `xnat_home_dir` at the inventory level (for the `xnat` group)

Is that all correct / did I miss anything?

2024-03-26 18:45 UTC, merged