Switch to official Rocky image
UCL-MIRSG/ansible-collection-infra pull request #61
Opened 2024-01-22 11:38 UTC by paddyroddy

2024-01-22 17:51 UTC, drmatthews requested changes
Looks good. I removed remaining occurrences of `MOLECULE_DOCKER_IMAGE` for consistency.

2024-01-22 17:51 UTC, drmatthews commented on molecule_configs/rocky9_base_config.yml
> +    image: ${MOLECULE_DOCKER_IMAGE:-rockylinux/rockylinux:9-ubi-init}
```suggestion
    image: rockylinux/rockylinux:9-ubi-init
```

2024-01-22 17:51 UTC, drmatthews commented on playbooks/molecule/rocky9_monitoring/molecule.yml
> +    image: ${MOLECULE_DOCKER_IMAGE:-rockylinux/rockylinux:9-ubi-init}
```suggestion
    image: rockylinux/rockylinux:9-ubi-init
```

2024-01-22 17:51 UTC, drmatthews commented on roles/nginx/molecule/rocky9/molecule.yml
> +    image: ${MOLECULE_DOCKER_IMAGE:-rockylinux/rockylinux:9-ubi-init}
```suggestion
    image: rockylinux/rockylinux:9-ubi-init
```

2024-01-22 18:26 UTC, p-j-smith requested changes
looks good! Although there are a few more roles that need the prepare steps added:
- [X] firewalld
- [X] postgresql
- [X] provision
- [X] provision_accounts

Side note (and can be done in a different PR), but the workflows for testing roles should run when the molecule base configs change (i.e. add `- "molecule_configs/*"` to the paths)

2024-01-23 14:46 UTC, paddyroddy commented
> looks good! Although there are a few more roles that need the prepare steps added:
> 
>     * [x]  firewalld
> 
>     * [x]  postgresql
> 
>     * [x]  provision
> 
>     * [x]  provision_accounts
> 
> 
> Side note (and can be done in a different PR), but the workflows for testing roles should run when the molecule base configs change (i.e. add `- "molecule_configs/*"` to the paths)

I've done all of this but can see it's failing for `sudo` missing reasons, any ideas?

2024-01-23 15:06 UTC, p-j-smith commented
I've done all of this but can see it's failing for sudo missing reasons, any ideas?

I haven't looked at monitoring, but for postgresql the sudo installation is happening after the `mirsg.infrastructure.provision` role runs:
https://github.com/UCL-MIRSG/ansible-collection-infra/blob/e8cbd31ec234296e12d0a0900e7b8c0533659c8b/roles/postgresql/molecule/resources/prepare.yml#L7C1-L11C23
You'll need to add a pre-task to install sudo so it runs before the role:
```yaml
  pre_tasks:
    - name: Install sudo
      ansible.builtin.package:
        name: sudo
        state: present
```

2024-01-23 15:12 UTC, p-j-smith commented
For the monitoring there's a [separate prepare playbook](https://github.com/UCL-MIRSG/ansible-collection-infra/blob/main/playbooks/molecule/resources/monitoring/prepare.yml) that needs the sudo installation added

2024-01-23 16:30 UTC, paddyroddy commented
> For the monitoring there's a [separate prepare playbook](https://github.com/UCL-MIRSG/ansible-collection-infra/blob/main/playbooks/molecule/resources/monitoring/prepare.yml?rgh-link-date=2024-01-23T15%3A12%3A52Z) that needs the sudo installation added

Of course, I should have known!

2024-01-23 16:36 UTC, paddyroddy commented
Now getting for `molecule-monitoring (rocky9_monitoring)`
![image](https://github.com/UCL-MIRSG/ansible-collection-infra/assets/15052188/0d2abe2e-6cd1-4f3d-b465-1f032df3f49a)

2024-01-24 10:17 UTC, p-j-smith commented
It looks like the issue is that the SSL certificates are being generated before cryptograph is installed:
https://github.com/UCL-MIRSG/ansible-collection-infra/blob/2e26c0393255179a27a76ed865db48850694b194/playbooks/molecule/resources/monitoring/converge.yml#L7-L12
I think you'll need to add the role `mirsg.infrastructure.install_python` before `mirsg.infrastructure.ssl_certificates`

2024-01-24 12:07 UTC, paddyroddy commented
> I think you'll need to add the role `mirsg.infrastructure.install_python` before `mirsg.infrastructure.ssl_certificates`

This was the error this time
![image](https://github.com/UCL-MIRSG/ansible-collection-infra/assets/15052188/541c1e23-1b31-455f-b341-6f8f4b665145)

I will try pulling in your latest changes

2024-01-24 12:15 UTC, paddyroddy commented
I'm going to need help
![image](https://github.com/UCL-MIRSG/ansible-collection-infra/assets/15052188/195e5301-c89c-4cd5-93a9-19fb223d5bec)

2024-01-24 16:46 UTC, paddyroddy commented
Would either of you @drmatthews @p-j-smith be able to look into this? I don't know `molecule`, so I'm a bit lost. This is my [XNAT Dockerfile used in SRR](https://github.com/UCL-MIRSG/UCLH-MPBE-SRR-XNAT/blob/main/docker/xnat.Dockerfile)

2024-01-24 18:30 UTC, drmatthews commented
Sorry for the lack of a response @paddyroddy, been in meetings all day. Will try to look tomorrow.

2024-01-31 14:48 UTC, paddyroddy commented
Anyone had a chance to look?

2024-01-31 15:36 UTC, drmatthews commented
Apologies @paddyroddy - I've been tied up with a few other things. It looks like a `cgroup` thing but I need to look in more detail. The monitoring consists of a set of Docker containers running on the monitoring host. Some of them require `cgroup` volumes to be mounted (in the tests the monitoring host is itself a Docker container). There isn't a lot going on in the [Docker file we're using](https://github.com/geerlingguy/docker-rockylinux9-ansible/blob/master/Dockerfile) but it does define this `VOLUME`:

```
VOLUME ["/sys/fs/cgroup"]
```

But the purpose of that is just make sure that the volume is always mounted when a container is created. This volume is explicitly set in `rocky9_base_config.yml`:

https://github.com/UCL-MIRSG/ansible-collection-infra/blob/f39813a234b5fc1dc3e995c9c57b12901bb70871/molecule_configs/rocky9_base_config.yml#L21-L23

So it is unclear why it isn't working. I'll need to find some time to test some options for the volumes being mounted in the `cadvisor` container (this is throwing the error) and some options for the modifying the Docker file for the image used by molecule.

2024-01-31 15:39 UTC, paddyroddy commented
I'm using the same `cgroup` thing in SRR https://github.com/UCL-MIRSG/UCLH-MPBE-SRR-XNAT/blob/1cb6f5e1e3e38db61827d7ff3ad24f3fac0f17a3/docker-compose.yml#L65, and had spotted it in your config so didn't think that was causing the issue.

2024-01-31 15:42 UTC, drmatthews commented
The error says `error mounting \"/sys/fs/cgroup/cpu,cpuacct\" to rootfs`. This a volume being mounted into the `cadvisor` container from the molecule `mserv` container.

2024-02-01 18:41 UTC, drmatthews commented
> The error says error mounting \"/sys/fs/cgroup/cpu,cpuacct\" to rootfs. This a volume being mounted into the cadvisor container from the molecule mserv container.

Turns out I had conflicting volumes defined for the `cadvisor` container. Don't know why it wasn't picked up before.

2024-02-01 18:56 UTC, drmatthews approved these changes
Looks good - sorry for the wait.

2024-02-06 16:42 UTC, p-j-smith approved these changes
nice 🎉

2024-02-06 16:43 UTC, merged